class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirror99761'
        self.UnzipMirrorCommand = 'unzip99761'
        self.TarMirrorCommand = 'tar99761'
        self.ZipMirrorCommand = 'zip99761'
        self.CancelMirror = 'cancel99761'
        self.CancelAllCommand = 'cnlall99761'
        self.ListCommand = 'list9976'
        self.StatusCommand = 'status'
        self.AuthorizedUsersCommand = 'users9976'
        self.AuthorizeCommand = 'auth'
        self.UnAuthorizeCommand = 'unauth'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart2'
        self.StatsCommand = 'stat99761'
        self.HelpCommand = 'hlp99761'
        self.LogCommand = 'log2'
        self.SpeedCommand = 'speedtest99761'
        self.CloneCommand = 'clone'
        self.CountCommand = 'count'
        self.WatchCommand = 'watch99761'
        self.TarWatchCommand = 'tarwatch99761'
        self.DeleteCommand = 'delet'
        self.ConfigMenuCommand = 'config99761'
        self.ShellCommand = 'shell'
        self.UpdateCommand = 'update99761'
        self.ExecHelpCommand = 'exechelp99761'
        self.TsHelpCommand = 'tshelp99761'
        self.GDTOTCommand = 'gdtot'

BotCommands = _BotCommands()
